// This file is auto-generated by @hey-api/openapi-ts

export const $ProblemDetail = {
    type: 'object',
    required: ['type', 'title', 'status'],
    properties: {
        type: {
            type: 'string',
            description: 'URI reference identifying the problem type',
            example: 'https://api.foodflow.io/errors/validation-error'
        },
        title: {
            type: 'string',
            description: 'Short human-readable summary',
            example: 'Validation Error'
        },
        status: {
            type: 'integer',
            description: 'HTTP status code'
        },
        detail: {
            type: 'string',
            description: 'Human-readable explanation',
            example: 'Email is already registered'
        },
        instance: {
            type: 'string',
            description: 'URI of the specific occurrence'
        },
        errors: {
            type: 'array',
            description: 'Field-level validation errors',
            items: {
                type: 'object',
                properties: {
                    field: {
                        type: 'string'
                    },
                    message: {
                        type: 'string'
                    },
                    code: {
                        type: 'string'
                    }
                }
            }
        }
    }
} as const;

export const $PaginationMeta = {
    type: 'object',
    required: ['total', 'page', 'limit', 'hasMore'],
    properties: {
        total: {
            type: 'integer',
            description: 'Total number of records'
        },
        page: {
            type: 'integer',
            minimum: 1
        },
        limit: {
            type: 'integer',
            minimum: 1,
            maximum: 100
        },
        hasMore: {
            type: 'boolean',
            description: 'Whether more pages exist'
        }
    }
} as const;

export const $RegisterRequest = {
    type: 'object',
    required: ['email', 'password', 'fullName'],
    properties: {
        email: {
            type: 'string',
            format: 'email',
            maxLength: 255
        },
        password: {
            type: 'string',
            minLength: 8,
            maxLength: 128
        },
        fullName: {
            type: 'string',
            maxLength: 100
        },
        phone: {
            type: 'string',
            maxLength: 20
        },
        role: {
            type: 'string',
            enum: ['customer', 'driver', 'restaurant'],
            default: 'customer'
        }
    }
} as const;

export const $LoginRequest = {
    type: 'object',
    required: ['email', 'password'],
    properties: {
        email: {
            type: 'string',
            format: 'email'
        },
        password: {
            type: 'string'
        }
    }
} as const;

export const $RefreshRequest = {
    type: 'object',
    required: ['refreshToken'],
    properties: {
        refreshToken: {
            type: 'string',
            description: 'Opaque rotating refresh token'
        }
    }
} as const;

export const $AuthResult = {
    type: 'object',
    required: ['accessToken', 'refreshToken', 'user'],
    properties: {
        accessToken: {
            type: 'string',
            description: 'JWT access token (Ed25519-signed)'
        },
        refreshToken: {
            type: 'string',
            description: 'Opaque rotating refresh token'
        },
        expiresIn: {
            type: 'integer',
            description: 'Access token TTL in seconds',
            example: 900
        },
        user: {
            '$ref': '#/components/schemas/SanitizedUser'
        }
    }
} as const;

export const $SanitizedUser = {
    type: 'object',
    required: ['id', 'email', 'fullName', 'role', 'isActive'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        email: {
            type: 'string',
            format: 'email'
        },
        fullName: {
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        role: {
            type: 'string',
            enum: ['customer', 'driver', 'restaurant', 'admin']
        },
        avatarUrl: {
            type: 'string',
            format: 'uri'
        },
        isActive: {
            type: 'boolean'
        },
        preferredLocale: {
            type: 'string',
            enum: ['vi', 'en', 'ja']
        }
    }
} as const;

export const $LogoutRequest = {
    type: 'object',
    properties: {
        refreshToken: {
            type: 'string',
            description: 'Token to invalidate'
        }
    }
} as const;

export const $JwksResponse = {
    type: 'object',
    required: ['keys'],
    properties: {
        keys: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    kty: {
                        type: 'string',
                        example: 'OKP'
                    },
                    crv: {
                        type: 'string',
                        example: 'Ed25519'
                    },
                    kid: {
                        type: 'string'
                    },
                    x: {
                        type: 'string'
                    },
                    use: {
                        type: 'string',
                        example: 'sig'
                    }
                }
            }
        }
    }
} as const;

export const $JwksVersionResponse = {
    type: 'object',
    required: ['version', 'rotatedAt'],
    properties: {
        version: {
            type: 'integer'
        },
        rotatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const $UserProfile = {
    type: 'object',
    required: ['id', 'email', 'fullName', 'role', 'createdAt'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        email: {
            type: 'string',
            format: 'email'
        },
        fullName: {
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        role: {
            type: 'string',
            enum: ['customer', 'driver', 'restaurant', 'admin']
        },
        avatarUrl: {
            type: 'string',
            format: 'uri'
        },
        preferredLocale: {
            type: 'string',
            enum: ['vi', 'en', 'ja']
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        customerProfile: {
            '$ref': '#/components/schemas/CustomerProfile'
        },
        driverProfile: {
            '$ref': '#/components/schemas/DriverProfile'
        },
        restaurantProfile: {
            '$ref': '#/components/schemas/RestaurantProfileBrief'
        }
    }
} as const;

export const $CustomerProfile = {
    type: 'object',
    properties: {
        totalOrders: {
            type: 'integer'
        },
        defaultAddress: {
            '$ref': '#/components/schemas/Address'
        }
    }
} as const;

export const $DriverProfile = {
    type: 'object',
    properties: {
        licenseNumber: {
            type: 'string'
        },
        vehicleType: {
            type: 'string',
            enum: ['motorbike', 'car', 'bicycle']
        },
        vehiclePlate: {
            type: 'string'
        },
        isOnline: {
            type: 'boolean'
        },
        isVerified: {
            type: 'boolean'
        },
        rating: {
            type: 'number',
            minimum: 1,
            maximum: 5
        },
        totalDeliveries: {
            type: 'integer'
        },
        totalEarnings: {
            type: 'integer',
            description: 'VND'
        }
    }
} as const;

export const $RestaurantProfileBrief = {
    type: 'object',
    properties: {
        restaurantId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const $UpdateUserRequest = {
    type: 'object',
    properties: {
        fullName: {
            type: 'string',
            maxLength: 100
        },
        phone: {
            type: 'string',
            maxLength: 20
        },
        preferredLocale: {
            type: 'string',
            enum: ['vi', 'en', 'ja']
        }
    }
} as const;

export const $AvatarUploadResponse = {
    type: 'object',
    required: ['url'],
    properties: {
        url: {
            type: 'string',
            format: 'uri'
        }
    }
} as const;

export const $Address = {
    type: 'object',
    required: ['id', 'label', 'addressLine', 'lat', 'lng'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        label: {
            type: 'string',
            example: 'Nha'
        },
        addressLine: {
            type: 'string',
            example: '123 Nguyễn Huệ, Quận 1'
        },
        lat: {
            type: 'number',
            format: 'double'
        },
        lng: {
            type: 'number',
            format: 'double'
        },
        isDefault: {
            type: 'boolean'
        }
    }
} as const;

export const $CreateAddressRequest = {
    type: 'object',
    required: ['label', 'addressLine', 'lat', 'lng'],
    properties: {
        label: {
            type: 'string'
        },
        addressLine: {
            type: 'string'
        },
        lat: {
            type: 'number',
            format: 'double'
        },
        lng: {
            type: 'number',
            format: 'double'
        },
        isDefault: {
            type: 'boolean'
        }
    }
} as const;

export const $UpdateAddressRequest = {
    type: 'object',
    properties: {
        label: {
            type: 'string'
        },
        addressLine: {
            type: 'string'
        },
        lat: {
            type: 'number',
            format: 'double'
        },
        lng: {
            type: 'number',
            format: 'double'
        },
        isDefault: {
            type: 'boolean'
        }
    }
} as const;

export const $RestaurantSummary = {
    type: 'object',
    required: ['id', 'name', 'slug', 'addressLine', 'city', 'cuisineTypes', 'priceRange', 'rating', 'prepTimeAvgMinutes', 'isOpen'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        slug: {
            type: 'string'
        },
        logoUrl: {
            type: 'string',
            format: 'uri'
        },
        coverUrl: {
            type: 'string',
            format: 'uri'
        },
        addressLine: {
            type: 'string'
        },
        city: {
            type: 'string'
        },
        district: {
            type: 'string'
        },
        cuisineTypes: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        priceRange: {
            type: 'string',
            enum: ['$', '$$', '$$$']
        },
        rating: {
            type: 'number',
            minimum: 1,
            maximum: 5
        },
        totalReviews: {
            type: 'integer'
        },
        prepTimeAvgMinutes: {
            type: 'integer'
        },
        isOpen: {
            type: 'boolean'
        },
        minOrderAmount: {
            type: 'integer',
            description: 'VND'
        },
        distanceKm: {
            type: 'number',
            description: 'Distance from query point'
        }
    }
} as const;

export const $RestaurantDetail = {
    allOf: [
        {
            '$ref': '#/components/schemas/RestaurantSummary'
        }
    ],
    type: 'object',
    required: ['phone', 'openingHours', 'description'],
    properties: {
        phone: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        isActive: {
            type: 'boolean'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        openingHours: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    dayOfWeek: {
                        type: 'integer',
                        minimum: 0,
                        maximum: 6
                    },
                    openTime: {
                        type: 'string',
                        example: '07:00'
                    },
                    closeTime: {
                        type: 'string',
                        example: '22:00'
                    },
                    isClosed: {
                        type: 'boolean'
                    }
                }
            }
        }
    }
} as const;

export const $RestaurantListResponse = {
    type: 'object',
    required: ['data', 'meta'],
    properties: {
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/RestaurantSummary'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PaginationMeta'
        }
    }
} as const;

export const $MenuCategory = {
    type: 'object',
    required: ['id', 'name', 'sortOrder'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        sortOrder: {
            type: 'integer'
        }
    }
} as const;

export const $MenuItem = {
    type: 'object',
    required: ['id', 'name', 'basePrice', 'isAvailable'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        categoryId: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        imageUrl: {
            type: 'string',
            format: 'uri'
        },
        basePrice: {
            type: 'integer',
            description: 'VND'
        },
        isAvailable: {
            type: 'boolean'
        },
        isPopular: {
            type: 'boolean'
        },
        options: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/MenuItemOption'
            }
        }
    }
} as const;

export const $MenuResponse = {
    type: 'object',
    required: ['categories', 'items'],
    properties: {
        categories: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/MenuCategory'
            }
        },
        items: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/MenuItem'
            }
        }
    }
} as const;

export const $MenuItemOption = {
    type: 'object',
    required: ['id', 'name', 'isRequired', 'isMultiple', 'values'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        isRequired: {
            type: 'boolean'
        },
        isMultiple: {
            type: 'boolean'
        },
        values: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    id: {
                        type: 'string',
                        format: 'uuid'
                    },
                    value: {
                        type: 'string'
                    },
                    priceModifier: {
                        type: 'integer',
                        description: 'VND'
                    }
                }
            }
        }
    }
} as const;

export const $CreateCategoryRequest = {
    type: 'object',
    required: ['name'],
    properties: {
        name: {
            type: 'string',
            maxLength: 100
        },
        sortOrder: {
            type: 'integer'
        }
    }
} as const;

export const $UpdateCategoryRequest = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        sortOrder: {
            type: 'integer'
        }
    }
} as const;

export const $CreateMenuItemRequest = {
    type: 'object',
    required: ['categoryId', 'name', 'basePrice'],
    properties: {
        name: {
            type: 'string',
            maxLength: 200
        },
        description: {
            type: 'string'
        },
        imageUrl: {
            type: 'string',
            format: 'uri'
        },
        categoryId: {
            type: 'string',
            format: 'uuid'
        },
        basePrice: {
            type: 'integer',
            minimum: 0,
            description: 'VND'
        },
        isAvailable: {
            type: 'boolean'
        },
        isPopular: {
            type: 'boolean'
        },
        options: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    name: {
                        type: 'string'
                    },
                    isRequired: {
                        type: 'boolean'
                    },
                    isMultiple: {
                        type: 'boolean'
                    },
                    values: {
                        type: 'array',
                        items: {
                            type: 'object',
                            properties: {
                                value: {
                                    type: 'string'
                                },
                                priceModifier: {
                                    type: 'integer',
                                    description: 'VND'
                                }
                            }
                        }
                    }
                }
            }
        }
    }
} as const;

export const $UpdateMenuItemRequest = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        imageUrl: {
            type: 'string',
            format: 'uri'
        },
        categoryId: {
            type: 'string',
            format: 'uuid'
        },
        basePrice: {
            type: 'integer',
            minimum: 0,
            description: 'VND'
        },
        isAvailable: {
            type: 'boolean'
        },
        isPopular: {
            type: 'boolean'
        }
    }
} as const;

export const $CartItem = {
    type: 'object',
    required: ['id', 'menuItemId', 'name', 'quantity', 'unitPrice'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        menuItemId: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        imageUrl: {
            type: 'string',
            format: 'uri'
        },
        quantity: {
            type: 'integer',
            minimum: 1
        },
        unitPrice: {
            type: 'integer',
            description: 'VND'
        },
        selectedOptions: {
            type: 'array',
            items: {
                type: 'object'
            }
        },
        notes: {
            type: 'string',
            maxLength: 300
        }
    }
} as const;

export const $CartResponse = {
    type: 'object',
    required: ['items', 'subtotal', 'itemCount'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        restaurantId: {
            type: 'string',
            format: 'uuid'
        },
        restaurantName: {
            type: 'string'
        },
        promotionCode: {
            type: 'string'
        },
        promotionDiscount: {
            type: 'integer',
            description: 'VND discount'
        },
        items: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CartItem'
            }
        },
        subtotal: {
            type: 'integer',
            description: 'VND'
        },
        itemCount: {
            type: 'integer'
        }
    }
} as const;

export const $AddCartItemRequest = {
    type: 'object',
    required: ['menuItemId', 'quantity', 'unitPrice'],
    properties: {
        menuItemId: {
            type: 'string',
            format: 'uuid'
        },
        quantity: {
            type: 'integer',
            minimum: 1
        },
        unitPrice: {
            type: 'integer',
            description: 'VND'
        },
        selectedOptions: {
            type: 'array',
            items: {
                type: 'object'
            }
        },
        notes: {
            type: 'string'
        }
    }
} as const;

export const $UpdateCartItemRequest = {
    type: 'object',
    properties: {
        quantity: {
            type: 'integer',
            minimum: 0
        },
        selectedOptions: {
            type: 'array',
            items: {
                type: 'object'
            }
        },
        notes: {
            type: 'string'
        }
    }
} as const;

export const $ApplyPromotionRequest = {
    type: 'object',
    required: ['code'],
    properties: {
        code: {
            type: 'string'
        }
    }
} as const;

export const $PlaceOrderRequest = {
    type: 'object',
    required: ['restaurantId', 'deliveryAddressId', 'paymentMethod', 'items'],
    properties: {
        restaurantId: {
            type: 'string',
            format: 'uuid'
        },
        deliveryAddressId: {
            type: 'string',
            format: 'uuid'
        },
        paymentMethod: {
            type: 'string',
            enum: ['cash', 'mock_wallet', 'sepay']
        },
        promotionCode: {
            type: 'string'
        },
        notes: {
            type: 'string',
            maxLength: 500
        },
        items: {
            type: 'array',
            items: {
                type: 'object',
                required: ['menuItemId', 'quantity', 'unitPrice'],
                properties: {
                    menuItemId: {
                        type: 'string',
                        format: 'uuid'
                    },
                    quantity: {
                        type: 'integer',
                        minimum: 1
                    },
                    unitPrice: {
                        type: 'integer',
                        description: 'VND (at time of order)'
                    },
                    selectedOptions: {
                        type: 'array',
                        items: {
                            type: 'object'
                        }
                    },
                    notes: {
                        type: 'string'
                    }
                }
            }
        }
    }
} as const;

export const $OrderResponse = {
    type: 'object',
    required: ['id', 'orderCode', 'status', 'subtotal', 'deliveryFee', 'total', 'paymentMethod', 'createdAt'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        orderCode: {
            type: 'string',
            example: 'FF2806A1B2C3'
        },
        customerId: {
            type: 'string',
            format: 'uuid'
        },
        restaurantId: {
            type: 'string',
            format: 'uuid'
        },
        restaurantName: {
            type: 'string'
        },
        driverId: {
            type: 'string',
            format: 'uuid'
        },
        driverName: {
            type: 'string'
        },
        deliveryAddress: {
            '$ref': '#/components/schemas/Address'
        },
        status: {
            type: 'string',
            enum: ['created', 'pending_payment', 'paid', 'restaurant_pending', 'restaurant_accepted', 'preparing', 'ready_for_pickup', 'driver_assigned', 'driver_arriving_restaurant', 'picked_up', 'delivering', 'delivered', 'completed', 'cancelled', 'refunded']
        },
        items: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    id: {
                        type: 'string',
                        format: 'uuid'
                    },
                    nameSnapshot: {
                        type: 'string'
                    },
                    quantity: {
                        type: 'integer'
                    },
                    unitPrice: {
                        type: 'integer',
                        description: 'VND'
                    },
                    selectedOptions: {
                        type: 'array',
                        items: {
                            type: 'object'
                        }
                    }
                }
            }
        },
        subtotal: {
            type: 'integer',
            description: 'VND'
        },
        deliveryFee: {
            type: 'integer',
            description: 'VND'
        },
        promotionDiscount: {
            type: 'integer',
            description: 'VND'
        },
        total: {
            type: 'integer',
            description: 'VND'
        },
        paymentMethod: {
            type: 'string',
            enum: ['cash', 'mock_wallet', 'sepay']
        },
        paymentStatus: {
            type: 'string',
            enum: ['pending', 'completed', 'failed', 'refunded']
        },
        notes: {
            type: 'string'
        },
        estimatedPrepTimeMinutes: {
            type: 'integer'
        },
        estimatedDeliveryTimeMinutes: {
            type: 'integer'
        },
        statusHistory: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/StatusHistoryEntry'
            }
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const $StatusHistoryEntry = {
    type: 'object',
    properties: {
        status: {
            type: 'string'
        },
        changedBy: {
            type: 'string'
        },
        note: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const $OrderListResponse = {
    type: 'object',
    required: ['data', 'meta'],
    properties: {
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/OrderResponse'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PaginationMeta'
        }
    }
} as const;

export const $CancelOrderRequest = {
    type: 'object',
    properties: {
        reason: {
            type: 'string'
        }
    }
} as const;

export const $UpdateOrderStatusRequest = {
    type: 'object',
    required: ['status'],
    properties: {
        status: {
            type: 'string',
            enum: ['restaurant_accepted', 'preparing', 'ready_for_pickup', 'picked_up', 'delivering', 'delivered']
        },
        note: {
            type: 'string'
        }
    }
} as const;

export const $CreateReviewRequest = {
    type: 'object',
    required: ['foodRating'],
    properties: {
        foodRating: {
            type: 'integer',
            minimum: 1,
            maximum: 5
        },
        deliveryRating: {
            type: 'integer',
            minimum: 1,
            maximum: 5
        },
        comment: {
            type: 'string'
        },
        photos: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uri'
            }
        }
    }
} as const;

export const $SettlementBatch = {
    type: 'object',
    required: ['id', 'periodStart', 'periodEnd', 'totalAmount', 'status', 'createdAt'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        periodStart: {
            type: 'string',
            format: 'date-time'
        },
        periodEnd: {
            type: 'string',
            format: 'date-time'
        },
        totalAmount: {
            type: 'integer',
            description: 'VND'
        },
        status: {
            type: 'string',
            enum: ['pending', 'processing', 'completed', 'failed']
        },
        restaurantCount: {
            type: 'integer'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const $SettleRequest = {
    type: 'object',
    required: ['batchId', 'action'],
    properties: {
        batchId: {
            type: 'string',
            format: 'uuid'
        },
        action: {
            type: 'string',
            enum: ['settle', 'retry', 'force']
        }
    }
} as const;

export const $ReviewResponse = {
    type: 'object',
    required: ['id', 'orderId', 'foodRating', 'createdAt'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        orderId: {
            type: 'string',
            format: 'uuid'
        },
        customerId: {
            type: 'string',
            format: 'uuid'
        },
        customerName: {
            type: 'string'
        },
        foodRating: {
            type: 'integer',
            minimum: 1,
            maximum: 5
        },
        deliveryRating: {
            type: 'integer',
            minimum: 1,
            maximum: 5
        },
        comment: {
            type: 'string'
        },
        photos: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uri'
            }
        },
        reply: {
            type: 'string'
        },
        replyAt: {
            type: 'string',
            format: 'date-time'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const $ReviewListResponse = {
    type: 'object',
    required: ['data', 'meta'],
    properties: {
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ReviewResponse'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PaginationMeta'
        }
    }
} as const;

export const $ReviewPhotoUploadUrlResponse = {
    type: 'object',
    required: ['uploadUrl', 'key'],
    properties: {
        uploadUrl: {
            type: 'string',
            format: 'uri'
        },
        key: {
            type: 'string'
        }
    }
} as const;

export const $RestaurantReplyRequest = {
    type: 'object',
    required: ['reply'],
    properties: {
        reply: {
            type: 'string',
            maxLength: 500
        }
    }
} as const;

export const $AdminHideRequest = {
    type: 'object',
    required: ['reason'],
    properties: {
        reason: {
            type: 'string',
            maxLength: 200
        }
    }
} as const;

export const $GoOnlineRequest = {
    type: 'object',
    required: ['lat', 'lng'],
    properties: {
        lat: {
            type: 'number',
            format: 'double'
        },
        lng: {
            type: 'number',
            format: 'double'
        }
    }
} as const;

export const $DriverEarningsResponse = {
    type: 'object',
    required: ['period', 'totalEarnings', 'deliveryCount', 'tips'],
    properties: {
        period: {
            type: 'string',
            enum: ['today', 'week', 'month']
        },
        totalEarnings: {
            type: 'integer',
            description: 'VND'
        },
        deliveryCount: {
            type: 'integer'
        },
        tips: {
            type: 'integer',
            description: 'VND'
        },
        breakdown: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    date: {
                        type: 'string',
                        format: 'date'
                    },
                    earnings: {
                        type: 'integer',
                        description: 'VND'
                    },
                    deliveries: {
                        type: 'integer'
                    }
                }
            }
        }
    }
} as const;

export const $DriverIncentivesResponse = {
    type: 'object',
    properties: {
        activeIncentives: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    id: {
                        type: 'string',
                        format: 'uuid'
                    },
                    name: {
                        type: 'string'
                    },
                    description: {
                        type: 'string'
                    },
                    targetDeliveries: {
                        type: 'integer'
                    },
                    bonusAmount: {
                        type: 'integer',
                        description: 'VND'
                    },
                    progress: {
                        type: 'integer'
                    },
                    expiresAt: {
                        type: 'string',
                        format: 'date-time'
                    }
                }
            }
        }
    }
} as const;

export const $WalletSnapshot = {
    type: 'object',
    required: ['balance', 'pendingTopups'],
    properties: {
        balance: {
            type: 'integer',
            description: 'Available balance in VND (excludes pending topups per F8)'
        },
        pendingTopups: {
            type: 'integer',
            description: 'Pending topup amount in VND (not yet confirmed)'
        },
        recentTransactions: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    id: {
                        type: 'string',
                        format: 'uuid'
                    },
                    amountDelta: {
                        type: 'integer',
                        description: 'VND (positive=credit, negative=debit)'
                    },
                    type: {
                        type: 'string',
                        enum: ['credit', 'debit']
                    },
                    reason: {
                        type: 'string'
                    },
                    refId: {
                        type: 'string',
                        format: 'uuid'
                    },
                    createdAt: {
                        type: 'string',
                        format: 'date-time'
                    }
                }
            }
        }
    }
} as const;

export const $LoyaltySnapshot = {
    type: 'object',
    required: ['points', 'tier'],
    properties: {
        points: {
            type: 'integer'
        },
        tier: {
            type: 'string',
            enum: ['bronze', 'silver', 'gold', 'platinum']
        },
        nextTierPoints: {
            type: 'integer'
        },
        recentTransactions: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    id: {
                        type: 'string',
                        format: 'uuid'
                    },
                    points: {
                        type: 'integer'
                    },
                    type: {
                        type: 'string',
                        enum: ['credit', 'debit']
                    },
                    description: {
                        type: 'string'
                    },
                    createdAt: {
                        type: 'string',
                        format: 'date-time'
                    }
                }
            }
        }
    }
} as const;

export const $ReferralSnapshot = {
    type: 'object',
    required: ['code', 'totalRewards', 'successfulReferrals'],
    properties: {
        code: {
            type: 'string',
            example: 'FF28A1B2'
        },
        totalRewards: {
            type: 'integer',
            description: 'VND'
        },
        successfulReferrals: {
            type: 'integer'
        },
        recentRedemptions: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    id: {
                        type: 'string',
                        format: 'uuid'
                    },
                    rewardAmount: {
                        type: 'integer',
                        description: 'VND'
                    },
                    redeemedAt: {
                        type: 'string',
                        format: 'date-time'
                    }
                }
            }
        }
    }
} as const;

export const $PromotionResponse = {
    type: 'object',
    required: ['id', 'code', 'type', 'value', 'isActive', 'startsAt', 'expiresAt'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        code: {
            type: 'string',
            example: 'WELCOME50'
        },
        type: {
            type: 'string',
            enum: ['percentage', 'fixed', 'free_delivery']
        },
        value: {
            type: 'integer',
            description: 'VND (fixed) or percentage points'
        },
        minOrderAmount: {
            type: 'integer',
            description: 'VND'
        },
        maxDiscount: {
            type: 'integer',
            description: 'VND'
        },
        usageLimit: {
            type: 'integer'
        },
        usageCount: {
            type: 'integer'
        },
        maxPerUser: {
            type: 'integer'
        },
        firstOrderOnly: {
            type: 'boolean'
        },
        isActive: {
            type: 'boolean'
        },
        startsAt: {
            type: 'string',
            format: 'date-time'
        },
        expiresAt: {
            type: 'string',
            format: 'date-time'
        },
        discountAmount: {
            type: 'integer',
            description: 'Calculated discount for current user/cart (if applicable)'
        }
    }
} as const;

export const $CreatePromotionRequest = {
    type: 'object',
    required: ['code', 'type', 'value', 'usageLimit', 'startsAt', 'expiresAt'],
    properties: {
        code: {
            type: 'string',
            maxLength: 50
        },
        type: {
            type: 'string',
            enum: ['percentage', 'fixed', 'free_delivery']
        },
        value: {
            type: 'integer'
        },
        minOrderAmount: {
            type: 'integer',
            description: 'VND'
        },
        maxDiscount: {
            type: 'integer',
            description: 'VND'
        },
        usageLimit: {
            type: 'integer',
            minimum: 1
        },
        maxPerUser: {
            type: 'integer',
            minimum: 1
        },
        firstOrderOnly: {
            type: 'boolean'
        },
        restaurantId: {
            type: 'string',
            format: 'uuid'
        },
        startsAt: {
            type: 'string',
            format: 'date-time'
        },
        expiresAt: {
            type: 'string',
            format: 'date-time'
        },
        isActive: {
            type: 'boolean'
        }
    }
} as const;

export const $UpdatePromotionRequest = {
    type: 'object',
    properties: {
        value: {
            type: 'integer'
        },
        minOrderAmount: {
            type: 'integer',
            description: 'VND'
        },
        maxDiscount: {
            type: 'integer',
            description: 'VND'
        },
        usageLimit: {
            type: 'integer'
        },
        maxPerUser: {
            type: 'integer'
        },
        firstOrderOnly: {
            type: 'boolean'
        },
        startsAt: {
            type: 'string',
            format: 'date-time'
        },
        expiresAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const $PromotionListResponse = {
    type: 'object',
    required: ['data', 'meta'],
    properties: {
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/PromotionResponse'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PaginationMeta'
        }
    }
} as const;

export const $NotificationResponse = {
    type: 'object',
    required: ['id', 'title', 'body', 'type', 'isRead', 'createdAt'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        title: {
            type: 'string'
        },
        body: {
            type: 'string'
        },
        type: {
            type: 'string'
        },
        data: {
            type: 'object'
        },
        isRead: {
            type: 'boolean'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const $NotificationListResponse = {
    type: 'object',
    required: ['data', 'meta'],
    properties: {
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/NotificationResponse'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PaginationMeta'
        }
    }
} as const;

export const $RegisterFcmTokenRequest = {
    type: 'object',
    required: ['token', 'platform'],
    properties: {
        token: {
            type: 'string'
        },
        platform: {
            type: 'string',
            enum: ['ios', 'android', 'web']
        },
        deviceId: {
            type: 'string'
        }
    }
} as const;

export const $TrackingResponse = {
    type: 'object',
    required: ['orderId', 'driverLocation'],
    properties: {
        orderId: {
            type: 'string',
            format: 'uuid'
        },
        driverLocation: {
            type: 'object',
            properties: {
                lat: {
                    type: 'number',
                    format: 'double'
                },
                lng: {
                    type: 'number',
                    format: 'double'
                },
                heading: {
                    type: 'number'
                },
                lastUpdated: {
                    type: 'string',
                    format: 'date-time'
                }
            }
        },
        etaMinutes: {
            type: 'integer'
        },
        status: {
            type: 'string'
        },
        routePolyline: {
            type: 'string'
        }
    }
} as const;

export const $DashboardResponse = {
    type: 'object',
    required: ['totalOrders', 'totalRevenue', 'activeDrivers', 'activeCustomers', 'pendingTickets'],
    properties: {
        totalOrders: {
            type: 'integer'
        },
        totalRevenue: {
            type: 'integer',
            description: 'VND'
        },
        activeDrivers: {
            type: 'integer'
        },
        activeCustomers: {
            type: 'integer'
        },
        pendingTickets: {
            type: 'integer'
        },
        todayOrders: {
            type: 'integer'
        },
        todayRevenue: {
            type: 'integer',
            description: 'VND'
        }
    }
} as const;

export const $TopRestaurantEntry = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        orderCount: {
            type: 'integer'
        },
        revenue: {
            type: 'integer',
            description: 'VND'
        }
    }
} as const;

export const $RevenueChartEntry = {
    type: 'object',
    properties: {
        date: {
            type: 'string',
            format: 'date'
        },
        revenue: {
            type: 'integer',
            description: 'VND'
        },
        orders: {
            type: 'integer'
        }
    }
} as const;

export const $AdminUserEntry = {
    type: 'object',
    required: ['id', 'email', 'fullName', 'role', 'isActive', 'createdAt'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        email: {
            type: 'string',
            format: 'email'
        },
        fullName: {
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        role: {
            type: 'string',
            enum: ['customer', 'driver', 'restaurant', 'admin']
        },
        isActive: {
            type: 'boolean'
        },
        failedLoginCount: {
            type: 'integer'
        },
        lockedUntil: {
            type: 'string',
            format: 'date-time'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const $AdminUserListResponse = {
    type: 'object',
    required: ['data', 'meta'],
    properties: {
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/AdminUserEntry'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PaginationMeta'
        }
    }
} as const;

export const $ToggleUserStatusRequest = {
    type: 'object',
    required: ['isActive'],
    properties: {
        isActive: {
            type: 'boolean'
        }
    }
} as const;

export const $AdminRestaurantEntry = {
    type: 'object',
    required: ['id', 'name', 'slug', 'city', 'cuisineTypes', 'isActive', 'isOpen', 'rating', 'createdAt'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        slug: {
            type: 'string'
        },
        city: {
            type: 'string'
        },
        district: {
            type: 'string'
        },
        cuisineTypes: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        isActive: {
            type: 'boolean'
        },
        isOpen: {
            type: 'boolean'
        },
        rating: {
            type: 'number'
        },
        totalOrders: {
            type: 'integer'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const $AdminRestaurantListResponse = {
    type: 'object',
    required: ['data', 'meta'],
    properties: {
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/AdminRestaurantEntry'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PaginationMeta'
        }
    }
} as const;

export const $ToggleRestaurantStatusRequest = {
    type: 'object',
    required: ['isActive'],
    properties: {
        isActive: {
            type: 'boolean'
        }
    }
} as const;

export const $SupportTicketEntry = {
    type: 'object',
    required: ['id', 'userId', 'issueType', 'summary', 'priority', 'status', 'createdAt'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        userId: {
            type: 'string',
            format: 'uuid'
        },
        userEmail: {
            type: 'string',
            format: 'email'
        },
        orderId: {
            type: 'string',
            format: 'uuid'
        },
        issueType: {
            type: 'string',
            enum: ['late_delivery', 'wrong_item', 'missing_item', 'driver_issue', 'refund_request', 'other']
        },
        summary: {
            type: 'string'
        },
        priority: {
            type: 'string',
            enum: ['low', 'medium', 'high', 'critical']
        },
        status: {
            type: 'string',
            enum: ['open', 'in_progress', 'resolved', 'closed']
        },
        assignedAdminId: {
            type: 'string',
            format: 'uuid'
        },
        resolutionNotes: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        resolvedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const $SupportTicketListResponse = {
    type: 'object',
    required: ['data', 'meta'],
    properties: {
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/SupportTicketEntry'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PaginationMeta'
        }
    }
} as const;

export const $UpdateSupportTicketRequest = {
    type: 'object',
    properties: {
        status: {
            type: 'string',
            enum: ['open', 'in_progress', 'resolved', 'closed']
        },
        assignedAdminId: {
            type: 'string',
            format: 'uuid'
        },
        resolutionNotes: {
            type: 'string'
        }
    }
} as const;

export const $AuditLogEntry = {
    type: 'object',
    required: ['id', 'adminId', 'action', 'targetType', 'ipAddress', 'createdAt'],
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        adminId: {
            type: 'string',
            format: 'uuid'
        },
        adminEmail: {
            type: 'string',
            format: 'email'
        },
        action: {
            type: 'string'
        },
        targetType: {
            type: 'string'
        },
        targetId: {
            type: 'string',
            format: 'uuid'
        },
        oldValue: {
            type: 'object'
        },
        newValue: {
            type: 'object'
        },
        ipAddress: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const $AuditLogListResponse = {
    type: 'object',
    required: ['data', 'meta'],
    properties: {
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/AuditLogEntry'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PaginationMeta'
        }
    }
} as const;

export const $DispatchHeatmapPoint = {
    type: 'object',
    properties: {
        lat: {
            type: 'number',
            format: 'double'
        },
        lng: {
            type: 'number',
            format: 'double'
        },
        weight: {
            type: 'integer'
        },
        area: {
            type: 'string'
        }
    }
} as const;

export const $DispatchHeatmapResponse = {
    type: 'object',
    required: ['points', 'generatedAt'],
    properties: {
        points: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/DispatchHeatmapPoint'
            }
        },
        generatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const $RestaurantKpiResponse = {
    type: 'object',
    required: ['restaurantId', 'restaurantName', 'period'],
    properties: {
        restaurantId: {
            type: 'string',
            format: 'uuid'
        },
        restaurantName: {
            type: 'string'
        },
        period: {
            type: 'string'
        },
        totalOrders: {
            type: 'integer'
        },
        totalRevenue: {
            type: 'integer',
            description: 'VND'
        },
        avgPrepTimeMinutes: {
            type: 'number'
        },
        avgRating: {
            type: 'number'
        },
        cancellationRate: {
            type: 'number'
        },
        topSellingItems: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    name: {
                        type: 'string'
                    },
                    quantity: {
                        type: 'integer'
                    }
                }
            }
        }
    }
} as const;

export const $ChatRequest = {
    type: 'object',
    required: ['message'],
    properties: {
        message: {
            type: 'string'
        },
        sessionId: {
            type: 'string',
            format: 'uuid'
        },
        orderId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const $ChatResponse = {
    type: 'object',
    properties: {
        reply: {
            type: 'string'
        },
        action: {
            type: 'string'
        },
        sessionId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const $WebhookOrderEvent = {
    type: 'object',
    required: ['orderId', 'event', 'userId'],
    properties: {
        orderId: {
            type: 'string',
            format: 'uuid'
        },
        event: {
            type: 'string'
        },
        userId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const $WebhookDriverDelay = {
    type: 'object',
    required: ['orderId', 'driverId', 'delayMinutes'],
    properties: {
        orderId: {
            type: 'string',
            format: 'uuid'
        },
        driverId: {
            type: 'string',
            format: 'uuid'
        },
        delayMinutes: {
            type: 'integer'
        }
    }
} as const;

export const $DelayedOrdersQuery = {
    type: 'object',
    properties: {
        threshold: {
            type: 'string',
            description: 'Minutes threshold'
        }
    }
} as const;

export const $StoppedDriversQuery = {
    type: 'object',
    properties: {
        minutes: {
            type: 'string',
            description: 'Inactive minutes'
        }
    }
} as const;

export const $LapsedCustomersQuery = {
    type: 'object',
    properties: {
        days: {
            type: 'string',
            description: 'Days since last order'
        }
    }
} as const;

export const $SepayWebhookResponse = {
    type: 'object',
    required: ['received'],
    properties: {
        received: {
            type: 'boolean'
        },
        duplicate: {
            type: 'boolean',
            description: 'True if already processed'
        }
    }
} as const;

export const $HealthResponse = {
    type: 'object',
    required: ['status', 'uptime', 'timestamp', 'components'],
    properties: {
        status: {
            type: 'string',
            enum: ['ok', 'degraded']
        },
        uptime: {
            type: 'number'
        },
        timestamp: {
            type: 'string',
            format: 'date-time'
        },
        components: {
            type: 'object',
            properties: {
                db: {
                    type: 'object',
                    properties: {
                        status: {
                            type: 'string',
                            enum: ['up', 'down']
                        },
                        latencyMs: {
                            type: 'number'
                        }
                    }
                },
                redis: {
                    type: 'object',
                    properties: {
                        status: {
                            type: 'string',
                            enum: ['up', 'down']
                        },
                        latencyMs: {
                            type: 'number'
                        }
                    }
                },
                minio: {
                    type: 'object',
                    properties: {
                        status: {
                            type: 'string',
                            enum: ['up', 'down']
                        },
                        latencyMs: {
                            type: 'number'
                        }
                    }
                }
            }
        }
    }
} as const;

export const $AnalyticsSummary = {
    type: 'object',
    required: ['periodStart', 'periodEnd', 'totalOrders', 'totalRevenue', 'totalCustomers', 'totalDrivers', 'cancellationRate'],
    properties: {
        periodStart: {
            type: 'string',
            format: 'date-time'
        },
        periodEnd: {
            type: 'string',
            format: 'date-time'
        },
        totalOrders: {
            type: 'integer'
        },
        totalRevenue: {
            type: 'integer',
            description: 'VND'
        },
        totalCustomers: {
            type: 'integer'
        },
        totalDrivers: {
            type: 'integer'
        },
        cancellationRate: {
            type: 'number',
            description: 'Fraction (0-1)'
        },
        avgOrderValue: {
            type: 'integer',
            description: 'VND'
        }
    }
} as const;

export const $PayoutLedgerEntry = {
    type: 'object',
    required: ['id', 'orderId', 'recipientType', 'amount', 'status', 'createdAt'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        orderId: {
            type: 'string',
            format: 'uuid'
        },
        recipientType: {
            type: 'string',
            enum: ['restaurant', 'driver']
        },
        recipientId: {
            type: 'string',
            format: 'uuid'
        },
        amount: {
            type: 'integer',
            description: 'VND'
        },
        currency: {
            type: 'string',
            example: 'VND'
        },
        status: {
            type: 'string',
            enum: ['pending', 'processing', 'completed', 'failed']
        },
        settlementBatchId: {
            type: 'string',
            format: 'uuid'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        settledAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const $DispatchOffer = {
    type: 'object',
    properties: {
        orderId: {
            type: 'string',
            format: 'uuid'
        },
        orderCode: {
            type: 'string'
        },
        restaurantName: {
            type: 'string'
        },
        pickupAddress: {
            type: 'string'
        },
        dropoffAddress: {
            type: 'string'
        },
        deliveryFee: {
            type: 'integer',
            description: 'VND'
        },
        distanceKm: {
            type: 'number'
        },
        expiresInSeconds: {
            type: 'integer'
        }
    }
} as const;

export const $AcceptOfferRequest = {
    type: 'object',
    required: ['orderId'],
    properties: {
        orderId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const $DeclineOfferRequest = {
    type: 'object',
    required: ['orderId'],
    properties: {
        orderId: {
            type: 'string',
            format: 'uuid'
        },
        reason: {
            type: 'string'
        }
    }
} as const;