// This file is auto-generated by @hey-api/openapi-ts

export type ProblemDetail = {
    /**
     * URI reference identifying the problem type
     */
    type: string;
    /**
     * Short human-readable summary
     */
    title: string;
    /**
     * HTTP status code
     */
    status: number;
    /**
     * Human-readable explanation
     */
    detail?: string;
    /**
     * URI of the specific occurrence
     */
    instance?: string;
    /**
     * Field-level validation errors
     */
    errors?: Array<{
        field?: string;
        message?: string;
        code?: string;
    }>;
};

export type PaginationMeta = {
    /**
     * Total number of records
     */
    total: number;
    page: number;
    limit: number;
    /**
     * Whether more pages exist
     */
    hasMore: boolean;
};

export type RegisterRequest = {
    email: string;
    password: string;
    fullName: string;
    phone?: string;
    role?: 'customer' | 'driver' | 'restaurant';
};

export type role = 'customer' | 'driver' | 'restaurant';

export type LoginRequest = {
    email: string;
    password: string;
};

export type RefreshRequest = {
    /**
     * Opaque rotating refresh token
     */
    refreshToken: string;
};

export type AuthResult = {
    /**
     * JWT access token (Ed25519-signed)
     */
    accessToken: string;
    /**
     * Opaque rotating refresh token
     */
    refreshToken: string;
    /**
     * Access token TTL in seconds
     */
    expiresIn?: number;
    user: SanitizedUser;
};

export type SanitizedUser = {
    id: string;
    email: string;
    fullName: string;
    phone?: string;
    role: 'customer' | 'driver' | 'restaurant' | 'admin';
    avatarUrl?: string;
    isActive: boolean;
    preferredLocale?: 'vi' | 'en' | 'ja';
};

export type role2 = 'customer' | 'driver' | 'restaurant' | 'admin';

export type preferredLocale = 'vi' | 'en' | 'ja';

export type LogoutRequest = {
    /**
     * Token to invalidate
     */
    refreshToken?: string;
};

export type JwksResponse = {
    keys: Array<{
        kty?: string;
        crv?: string;
        kid?: string;
        x?: string;
        use?: string;
    }>;
};

export type JwksVersionResponse = {
    version: number;
    rotatedAt: string;
};

export type UserProfile = {
    id: string;
    email: string;
    fullName: string;
    phone?: string;
    role: 'customer' | 'driver' | 'restaurant' | 'admin';
    avatarUrl?: string;
    preferredLocale?: 'vi' | 'en' | 'ja';
    createdAt: string;
    customerProfile?: CustomerProfile;
    driverProfile?: DriverProfile;
    restaurantProfile?: RestaurantProfileBrief;
};

export type CustomerProfile = {
    totalOrders?: number;
    defaultAddress?: Address;
};

export type DriverProfile = {
    licenseNumber?: string;
    vehicleType?: 'motorbike' | 'car' | 'bicycle';
    vehiclePlate?: string;
    isOnline?: boolean;
    isVerified?: boolean;
    rating?: number;
    totalDeliveries?: number;
    /**
     * VND
     */
    totalEarnings?: number;
};

export type vehicleType = 'motorbike' | 'car' | 'bicycle';

export type RestaurantProfileBrief = {
    restaurantId?: string;
};

export type UpdateUserRequest = {
    fullName?: string;
    phone?: string;
    preferredLocale?: 'vi' | 'en' | 'ja';
};

export type AvatarUploadResponse = {
    url: string;
};

export type Address = {
    id: string;
    label: string;
    addressLine: string;
    lat: number;
    lng: number;
    isDefault?: boolean;
};

export type CreateAddressRequest = {
    label: string;
    addressLine: string;
    lat: number;
    lng: number;
    isDefault?: boolean;
};

export type UpdateAddressRequest = {
    label?: string;
    addressLine?: string;
    lat?: number;
    lng?: number;
    isDefault?: boolean;
};

export type RestaurantSummary = {
    id: string;
    name: string;
    slug: string;
    logoUrl?: string;
    coverUrl?: string;
    addressLine: string;
    city: string;
    district?: string;
    cuisineTypes: Array<(string)>;
    priceRange: '$' | '$$' | '$$$';
    rating: number;
    totalReviews?: number;
    prepTimeAvgMinutes: number;
    isOpen: boolean;
    /**
     * VND
     */
    minOrderAmount?: number;
    /**
     * Distance from query point
     */
    distanceKm?: number;
};

export type priceRange = '$' | '$$' | '$$$';

export type RestaurantDetail = RestaurantSummary & {
    phone: string;
    description: string;
    isActive?: boolean;
    createdAt?: string;
    openingHours: Array<{
        dayOfWeek?: number;
        openTime?: string;
        closeTime?: string;
        isClosed?: boolean;
    }>;
};

export type RestaurantListResponse = {
    data: Array<RestaurantSummary>;
    meta: PaginationMeta;
};

export type MenuCategory = {
    id: string;
    name: string;
    sortOrder: number;
};

export type MenuItem = {
    id: string;
    categoryId?: string;
    name: string;
    description?: string;
    imageUrl?: string;
    /**
     * VND
     */
    basePrice: number;
    isAvailable: boolean;
    isPopular?: boolean;
    options?: Array<MenuItemOption>;
};

export type MenuResponse = {
    categories: Array<MenuCategory>;
    items: Array<MenuItem>;
};

export type MenuItemOption = {
    id: string;
    name: string;
    isRequired: boolean;
    isMultiple: boolean;
    values: Array<{
        id?: string;
        value?: string;
        /**
         * VND
         */
        priceModifier?: number;
    }>;
};

export type CreateCategoryRequest = {
    name: string;
    sortOrder?: number;
};

export type UpdateCategoryRequest = {
    name?: string;
    sortOrder?: number;
};

export type CreateMenuItemRequest = {
    name: string;
    description?: string;
    imageUrl?: string;
    categoryId: string;
    /**
     * VND
     */
    basePrice: number;
    isAvailable?: boolean;
    isPopular?: boolean;
    options?: Array<{
        name?: string;
        isRequired?: boolean;
        isMultiple?: boolean;
        values?: Array<{
            value?: string;
            /**
             * VND
             */
            priceModifier?: number;
        }>;
    }>;
};

export type UpdateMenuItemRequest = {
    name?: string;
    description?: string;
    imageUrl?: string;
    categoryId?: string;
    /**
     * VND
     */
    basePrice?: number;
    isAvailable?: boolean;
    isPopular?: boolean;
};

export type CartItem = {
    id: string;
    menuItemId: string;
    name: string;
    imageUrl?: string;
    quantity: number;
    /**
     * VND
     */
    unitPrice: number;
    selectedOptions?: Array<{
        [key: string]: unknown;
    }>;
    notes?: string;
};

export type CartResponse = {
    id?: string;
    restaurantId?: string;
    restaurantName?: string;
    promotionCode?: string;
    /**
     * VND discount
     */
    promotionDiscount?: number;
    items: Array<CartItem>;
    /**
     * VND
     */
    subtotal: number;
    itemCount: number;
};

export type AddCartItemRequest = {
    menuItemId: string;
    quantity: number;
    /**
     * VND
     */
    unitPrice: number;
    selectedOptions?: Array<{
        [key: string]: unknown;
    }>;
    notes?: string;
};

export type UpdateCartItemRequest = {
    quantity?: number;
    selectedOptions?: Array<{
        [key: string]: unknown;
    }>;
    notes?: string;
};

export type ApplyPromotionRequest = {
    code: string;
};

export type PlaceOrderRequest = {
    restaurantId: string;
    deliveryAddressId: string;
    paymentMethod: 'cash' | 'mock_wallet' | 'sepay';
    promotionCode?: string;
    notes?: string;
    items: Array<{
        menuItemId: string;
        quantity: number;
        /**
         * VND (at time of order)
         */
        unitPrice: number;
        selectedOptions?: Array<{
            [key: string]: unknown;
        }>;
        notes?: string;
    }>;
};

export type paymentMethod = 'cash' | 'mock_wallet' | 'sepay';

export type OrderResponse = {
    id: string;
    orderCode: string;
    customerId?: string;
    restaurantId?: string;
    restaurantName?: string;
    driverId?: string;
    driverName?: string;
    deliveryAddress?: Address;
    status: 'created' | 'pending_payment' | 'paid' | 'restaurant_pending' | 'restaurant_accepted' | 'preparing' | 'ready_for_pickup' | 'driver_assigned' | 'driver_arriving_restaurant' | 'picked_up' | 'delivering' | 'delivered' | 'completed' | 'cancelled' | 'refunded';
    items?: Array<{
        id?: string;
        nameSnapshot?: string;
        quantity?: number;
        /**
         * VND
         */
        unitPrice?: number;
        selectedOptions?: Array<{
            [key: string]: unknown;
        }>;
    }>;
    /**
     * VND
     */
    subtotal: number;
    /**
     * VND
     */
    deliveryFee: number;
    /**
     * VND
     */
    promotionDiscount?: number;
    /**
     * VND
     */
    total: number;
    paymentMethod: 'cash' | 'mock_wallet' | 'sepay';
    paymentStatus?: 'pending' | 'completed' | 'failed' | 'refunded';
    notes?: string;
    estimatedPrepTimeMinutes?: number;
    estimatedDeliveryTimeMinutes?: number;
    statusHistory?: Array<StatusHistoryEntry>;
    createdAt: string;
    updatedAt?: string;
};

export type status = 'created' | 'pending_payment' | 'paid' | 'restaurant_pending' | 'restaurant_accepted' | 'preparing' | 'ready_for_pickup' | 'driver_assigned' | 'driver_arriving_restaurant' | 'picked_up' | 'delivering' | 'delivered' | 'completed' | 'cancelled' | 'refunded';

export type paymentStatus = 'pending' | 'completed' | 'failed' | 'refunded';

export type StatusHistoryEntry = {
    status?: string;
    changedBy?: string;
    note?: string;
    createdAt?: string;
};

export type OrderListResponse = {
    data: Array<OrderResponse>;
    meta: PaginationMeta;
};

export type CancelOrderRequest = {
    reason?: string;
};

export type UpdateOrderStatusRequest = {
    status: 'restaurant_accepted' | 'preparing' | 'ready_for_pickup' | 'picked_up' | 'delivering' | 'delivered';
    note?: string;
};

export type status2 = 'restaurant_accepted' | 'preparing' | 'ready_for_pickup' | 'picked_up' | 'delivering' | 'delivered';

export type CreateReviewRequest = {
    foodRating: number;
    deliveryRating?: number;
    comment?: string;
    photos?: Array<(string)>;
};

export type SettlementBatch = {
    id: string;
    periodStart: string;
    periodEnd: string;
    /**
     * VND
     */
    totalAmount: number;
    status: 'pending' | 'processing' | 'completed' | 'failed';
    restaurantCount?: number;
    createdAt: string;
};

export type status3 = 'pending' | 'processing' | 'completed' | 'failed';

export type SettleRequest = {
    batchId: string;
    action: 'settle' | 'retry' | 'force';
};

export type action = 'settle' | 'retry' | 'force';

export type ReviewResponse = {
    id: string;
    orderId: string;
    customerId?: string;
    customerName?: string;
    foodRating: number;
    deliveryRating?: number;
    comment?: string;
    photos?: Array<(string)>;
    reply?: string;
    replyAt?: string;
    createdAt: string;
};

export type ReviewListResponse = {
    data: Array<ReviewResponse>;
    meta: PaginationMeta;
};

export type ReviewPhotoUploadUrlResponse = {
    uploadUrl: string;
    key: string;
};

export type RestaurantReplyRequest = {
    reply: string;
};

export type AdminHideRequest = {
    reason: string;
};

export type GoOnlineRequest = {
    lat: number;
    lng: number;
};

export type DriverEarningsResponse = {
    period: 'today' | 'week' | 'month';
    /**
     * VND
     */
    totalEarnings: number;
    deliveryCount: number;
    /**
     * VND
     */
    tips: number;
    breakdown?: Array<{
        date?: string;
        /**
         * VND
         */
        earnings?: number;
        deliveries?: number;
    }>;
};

export type period = 'today' | 'week' | 'month';

export type DriverIncentivesResponse = {
    activeIncentives?: Array<{
        id?: string;
        name?: string;
        description?: string;
        targetDeliveries?: number;
        /**
         * VND
         */
        bonusAmount?: number;
        progress?: number;
        expiresAt?: string;
    }>;
};

export type WalletSnapshot = {
    /**
     * Available balance in VND (excludes pending topups per F8)
     */
    balance: number;
    /**
     * Pending topup amount in VND (not yet confirmed)
     */
    pendingTopups: number;
    recentTransactions?: Array<{
        id?: string;
        /**
         * VND (positive=credit, negative=debit)
         */
        amountDelta?: number;
        type?: 'credit' | 'debit';
        reason?: string;
        refId?: string;
        createdAt?: string;
    }>;
};

export type LoyaltySnapshot = {
    points: number;
    tier: 'bronze' | 'silver' | 'gold' | 'platinum';
    nextTierPoints?: number;
    recentTransactions?: Array<{
        id?: string;
        points?: number;
        type?: 'credit' | 'debit';
        description?: string;
        createdAt?: string;
    }>;
};

export type tier = 'bronze' | 'silver' | 'gold' | 'platinum';

export type ReferralSnapshot = {
    code: string;
    /**
     * VND
     */
    totalRewards: number;
    successfulReferrals: number;
    recentRedemptions?: Array<{
        id?: string;
        /**
         * VND
         */
        rewardAmount?: number;
        redeemedAt?: string;
    }>;
};

export type PromotionResponse = {
    id: string;
    code: string;
    type: 'percentage' | 'fixed' | 'free_delivery';
    /**
     * VND (fixed) or percentage points
     */
    value: number;
    /**
     * VND
     */
    minOrderAmount?: number;
    /**
     * VND
     */
    maxDiscount?: number;
    usageLimit?: number;
    usageCount?: number;
    maxPerUser?: number;
    firstOrderOnly?: boolean;
    isActive: boolean;
    startsAt: string;
    expiresAt: string;
    /**
     * Calculated discount for current user/cart (if applicable)
     */
    discountAmount?: number;
};

export type type = 'percentage' | 'fixed' | 'free_delivery';

export type CreatePromotionRequest = {
    code: string;
    type: 'percentage' | 'fixed' | 'free_delivery';
    value: number;
    /**
     * VND
     */
    minOrderAmount?: number;
    /**
     * VND
     */
    maxDiscount?: number;
    usageLimit: number;
    maxPerUser?: number;
    firstOrderOnly?: boolean;
    restaurantId?: string;
    startsAt: string;
    expiresAt: string;
    isActive?: boolean;
};

export type UpdatePromotionRequest = {
    value?: number;
    /**
     * VND
     */
    minOrderAmount?: number;
    /**
     * VND
     */
    maxDiscount?: number;
    usageLimit?: number;
    maxPerUser?: number;
    firstOrderOnly?: boolean;
    startsAt?: string;
    expiresAt?: string;
};

export type PromotionListResponse = {
    data: Array<PromotionResponse>;
    meta: PaginationMeta;
};

export type NotificationResponse = {
    id: string;
    title: string;
    body: string;
    type: string;
    data?: {
        [key: string]: unknown;
    };
    isRead: boolean;
    createdAt: string;
};

export type NotificationListResponse = {
    data: Array<NotificationResponse>;
    meta: PaginationMeta;
};

export type RegisterFcmTokenRequest = {
    token: string;
    platform: 'ios' | 'android' | 'web';
    deviceId?: string;
};

export type platform = 'ios' | 'android' | 'web';

export type TrackingResponse = {
    orderId: string;
    driverLocation: {
        lat?: number;
        lng?: number;
        heading?: number;
        lastUpdated?: string;
    };
    etaMinutes?: number;
    status?: string;
    routePolyline?: string;
};

export type DashboardResponse = {
    totalOrders: number;
    /**
     * VND
     */
    totalRevenue: number;
    activeDrivers: number;
    activeCustomers: number;
    pendingTickets: number;
    todayOrders?: number;
    /**
     * VND
     */
    todayRevenue?: number;
};

export type TopRestaurantEntry = {
    id?: string;
    name?: string;
    orderCount?: number;
    /**
     * VND
     */
    revenue?: number;
};

export type RevenueChartEntry = {
    date?: string;
    /**
     * VND
     */
    revenue?: number;
    orders?: number;
};

export type AdminUserEntry = {
    id: string;
    email: string;
    fullName: string;
    phone?: string;
    role: 'customer' | 'driver' | 'restaurant' | 'admin';
    isActive: boolean;
    failedLoginCount?: number;
    lockedUntil?: string;
    createdAt: string;
};

export type AdminUserListResponse = {
    data: Array<AdminUserEntry>;
    meta: PaginationMeta;
};

export type ToggleUserStatusRequest = {
    isActive: boolean;
};

export type AdminRestaurantEntry = {
    id: string;
    name: string;
    slug: string;
    city: string;
    district?: string;
    cuisineTypes: Array<(string)>;
    isActive: boolean;
    isOpen: boolean;
    rating: number;
    totalOrders?: number;
    createdAt: string;
};

export type AdminRestaurantListResponse = {
    data: Array<AdminRestaurantEntry>;
    meta: PaginationMeta;
};

export type ToggleRestaurantStatusRequest = {
    isActive: boolean;
};

export type SupportTicketEntry = {
    id: string;
    userId: string;
    userEmail?: string;
    orderId?: string;
    issueType: 'late_delivery' | 'wrong_item' | 'missing_item' | 'driver_issue' | 'refund_request' | 'other';
    summary: string;
    priority: 'low' | 'medium' | 'high' | 'critical';
    status: 'open' | 'in_progress' | 'resolved' | 'closed';
    assignedAdminId?: string;
    resolutionNotes?: string;
    createdAt: string;
    resolvedAt?: string;
};

export type issueType = 'late_delivery' | 'wrong_item' | 'missing_item' | 'driver_issue' | 'refund_request' | 'other';

export type priority = 'low' | 'medium' | 'high' | 'critical';

export type status4 = 'open' | 'in_progress' | 'resolved' | 'closed';

export type SupportTicketListResponse = {
    data: Array<SupportTicketEntry>;
    meta: PaginationMeta;
};

export type UpdateSupportTicketRequest = {
    status?: 'open' | 'in_progress' | 'resolved' | 'closed';
    assignedAdminId?: string;
    resolutionNotes?: string;
};

export type AuditLogEntry = {
    id: number;
    adminId: string;
    adminEmail?: string;
    action: string;
    targetType: string;
    targetId?: string;
    oldValue?: {
        [key: string]: unknown;
    };
    newValue?: {
        [key: string]: unknown;
    };
    ipAddress: string;
    createdAt: string;
};

export type AuditLogListResponse = {
    data: Array<AuditLogEntry>;
    meta: PaginationMeta;
};

export type DispatchHeatmapPoint = {
    lat?: number;
    lng?: number;
    weight?: number;
    area?: string;
};

export type DispatchHeatmapResponse = {
    points: Array<DispatchHeatmapPoint>;
    generatedAt: string;
};

export type RestaurantKpiResponse = {
    restaurantId: string;
    restaurantName: string;
    period: string;
    totalOrders?: number;
    /**
     * VND
     */
    totalRevenue?: number;
    avgPrepTimeMinutes?: number;
    avgRating?: number;
    cancellationRate?: number;
    topSellingItems?: Array<{
        name?: string;
        quantity?: number;
    }>;
};

export type ChatRequest = {
    message: string;
    sessionId?: string;
    orderId?: string;
};

export type ChatResponse = {
    reply?: string;
    action?: string;
    sessionId?: string;
};

export type WebhookOrderEvent = {
    orderId: string;
    event: string;
    userId: string;
};

export type WebhookDriverDelay = {
    orderId: string;
    driverId: string;
    delayMinutes: number;
};

export type DelayedOrdersQuery = {
    /**
     * Minutes threshold
     */
    threshold?: string;
};

export type StoppedDriversQuery = {
    /**
     * Inactive minutes
     */
    minutes?: string;
};

export type LapsedCustomersQuery = {
    /**
     * Days since last order
     */
    days?: string;
};

export type SepayWebhookResponse = {
    received: boolean;
    /**
     * True if already processed
     */
    duplicate?: boolean;
};

export type HealthResponse = {
    status: 'ok' | 'degraded';
    uptime: number;
    timestamp: string;
    components: {
        db?: {
            status?: 'up' | 'down';
            latencyMs?: number;
        };
        redis?: {
            status?: 'up' | 'down';
            latencyMs?: number;
        };
        minio?: {
            status?: 'up' | 'down';
            latencyMs?: number;
        };
    };
};

export type status5 = 'ok' | 'degraded';

export type AnalyticsSummary = {
    periodStart: string;
    periodEnd: string;
    totalOrders: number;
    /**
     * VND
     */
    totalRevenue: number;
    totalCustomers: number;
    totalDrivers: number;
    /**
     * Fraction (0-1)
     */
    cancellationRate: number;
    /**
     * VND
     */
    avgOrderValue?: number;
};

export type PayoutLedgerEntry = {
    id: string;
    orderId: string;
    recipientType: 'restaurant' | 'driver';
    recipientId?: string;
    /**
     * VND
     */
    amount: number;
    currency?: string;
    status: 'pending' | 'processing' | 'completed' | 'failed';
    settlementBatchId?: string;
    createdAt: string;
    settledAt?: string;
};

export type recipientType = 'restaurant' | 'driver';

export type DispatchOffer = {
    orderId?: string;
    orderCode?: string;
    restaurantName?: string;
    pickupAddress?: string;
    dropoffAddress?: string;
    /**
     * VND
     */
    deliveryFee?: number;
    distanceKm?: number;
    expiresInSeconds?: number;
};

export type AcceptOfferRequest = {
    orderId: string;
};

export type DeclineOfferRequest = {
    orderId: string;
    reason?: string;
};

export type RegisterData = {
    requestBody: RegisterRequest;
};

export type RegisterResponse = AuthResult;

export type LoginData = {
    requestBody: LoginRequest;
};

export type LoginResponse = AuthResult;

export type RefreshTokenData = {
    requestBody: RefreshRequest;
};

export type RefreshTokenResponse = AuthResult;

export type LogoutData = {
    requestBody?: LogoutRequest;
};

export type LogoutResponse = {
    message?: string;
};

export type GetJwksResponse = JwksResponse;

export type GetJwksVersionResponse = JwksVersionResponse;

export type GetProfileResponse = UserProfile;

export type UpdateProfileData = {
    requestBody: UpdateUserRequest;
};

export type UpdateProfileResponse = UserProfile;

export type UploadAvatarData = {
    formData: {
        file: (Blob | File);
    };
};

export type UploadAvatarResponse = AvatarUploadResponse;

export type ListAddressesResponse = Array<Address>;

export type CreateAddressData = {
    requestBody: CreateAddressRequest;
};

export type CreateAddressResponse = Address;

export type UpdateAddressData = {
    id: string;
    requestBody: UpdateAddressRequest;
};

export type UpdateAddressResponse = Address;

export type DeleteAddressData = {
    id: string;
};

export type DeleteAddressResponse = void;

export type FindNearbyRestaurantsData = {
    lat: number;
    limit?: number;
    lng: number;
    page?: number;
    radiusKm?: number;
};

export type FindNearbyRestaurantsResponse = RestaurantListResponse;

export type SearchRestaurantsData = {
    city?: string;
    cuisine?: string;
    limit?: number;
    page?: number;
    q: string;
};

export type SearchRestaurantsResponse = RestaurantListResponse;

export type GetRestaurantDetailData = {
    id: string;
};

export type GetRestaurantDetailResponse = RestaurantDetail;

export type GetRestaurantMenuData = {
    id: string;
};

export type GetRestaurantMenuResponse = MenuResponse;

export type GetRestaurantReviewsData = {
    id: string;
    limit?: number;
    page?: number;
};

export type GetRestaurantReviewsResponse = ReviewListResponse;

export type GetOwnMenuResponse = MenuResponse;

export type CreateCategoryData = {
    requestBody: CreateCategoryRequest;
};

export type CreateCategoryResponse = MenuCategory;

export type UpdateCategoryData = {
    id: string;
    requestBody: UpdateCategoryRequest;
};

export type UpdateCategoryResponse = unknown;

export type DeleteCategoryData = {
    id: string;
};

export type DeleteCategoryResponse = void;

export type CreateMenuItemData = {
    requestBody: CreateMenuItemRequest;
};

export type CreateMenuItemResponse = MenuItem;

export type UpdateMenuItemData = {
    id: string;
    requestBody: UpdateMenuItemRequest;
};

export type UpdateMenuItemResponse = MenuItem;

export type DeleteMenuItemData = {
    id: string;
};

export type DeleteMenuItemResponse = void;

export type GetCartResponse = CartResponse;

export type ClearCartResponse = void;

export type AddCartItemData = {
    requestBody: AddCartItemRequest;
};

export type AddCartItemResponse = CartResponse;

export type UpdateCartItemData = {
    id: string;
    requestBody: UpdateCartItemRequest;
};

export type UpdateCartItemResponse = CartResponse;

export type RemoveCartItemData = {
    id: string;
};

export type RemoveCartItemResponse = void;

export type ApplyPromotionData = {
    requestBody: ApplyPromotionRequest;
};

export type ApplyPromotionResponse = CartResponse;

export type PlaceOrderData = {
    /**
     * Client-side UUID for idempotency (required even on signup per F4)
     */
    idempotencyKey: string;
    requestBody: PlaceOrderRequest;
};

export type PlaceOrderResponse = OrderResponse;

export type GetCustomerOrdersData = {
    limit?: number;
    page?: number;
    status?: string;
};

export type GetCustomerOrdersResponse = OrderListResponse;

export type GetOrderDetailData = {
    id: string;
};

export type GetOrderDetailResponse = OrderResponse;

export type GetOrderTrackingData = {
    id: string;
};

export type GetOrderTrackingResponse = TrackingResponse;

export type CancelOrderData = {
    id: string;
    requestBody?: CancelOrderRequest;
};

export type CancelOrderResponse = OrderResponse;

export type SubmitReviewData = {
    id: string;
    requestBody: CreateReviewRequest;
};

export type SubmitReviewResponse = ReviewResponse;

export type GetRestaurantOrdersData = {
    status?: string;
};

export type GetRestaurantOrdersResponse = Array<OrderResponse>;

export type UpdateRestaurantOrderStatusData = {
    id: string;
    requestBody: UpdateOrderStatusRequest;
};

export type UpdateRestaurantOrderStatusResponse = OrderResponse;

export type UpdateDriverOrderStatusData = {
    id: string;
    requestBody: UpdateOrderStatusRequest;
};

export type UpdateDriverOrderStatusResponse = OrderResponse;

export type GetPendingOffersResponse = Array<DispatchOffer>;

export type AcceptOfferData = {
    orderId: string;
    requestBody: AcceptOfferRequest;
};

export type AcceptOfferResponse = OrderResponse;

export type GoOnlineData = {
    requestBody: GoOnlineRequest;
};

export type GoOnlineResponse = unknown;

export type GoOfflineResponse = unknown;

export type GetDriverEarningsData = {
    period?: 'today' | 'week' | 'month';
};

export type GetDriverEarningsResponse = DriverEarningsResponse;

export type GetDriverIncentivesResponse = DriverIncentivesResponse;

export type GetDriverOrderHistoryData = {
    limit?: number;
    page?: number;
    status?: string;
};

export type GetDriverOrderHistoryResponse = OrderListResponse;

export type GetWalletResponse = WalletSnapshot;

export type TopupWalletData = {
    requestBody: {
        /**
         * VND, minimum 10,000
         */
        amount: number;
        returnUrl?: string;
    };
};

export type TopupWalletResponse = {
    transactionRef?: string;
    qrCodeUrl?: string;
    amount?: number;
    expiresAt?: string;
};

export type CheckTopupStatusData = {
    transactionRef: string;
};

export type CheckTopupStatusResponse = {
    status?: 'pending' | 'completed' | 'failed';
    amount?: number;
};

export type GetLoyaltyResponse = LoyaltySnapshot;

export type GetReferralResponse = ReferralSnapshot;

export type GetPromotionByCodeData = {
    code: string;
};

export type GetPromotionByCodeResponse = PromotionResponse;

export type ListPromotionsData = {
    limit?: number;
    page?: number;
};

export type ListPromotionsResponse = PromotionListResponse;

export type GetPhotoUploadUrlData = {
    contentType?: string;
};

export type GetPhotoUploadUrlResponse = ReviewPhotoUploadUrlResponse;

export type AdminHideReviewData = {
    id: string;
    requestBody: AdminHideRequest;
};

export type AdminHideReviewResponse = void;

export type RestaurantReplyData = {
    id: string;
    requestBody: RestaurantReplyRequest;
};

export type RestaurantReplyResponse = ReviewResponse;

export type GetNotificationsData = {
    limit?: number;
    page?: number;
};

export type GetNotificationsResponse = NotificationListResponse;

export type MarkAsReadData = {
    id: string;
};

export type MarkAsReadResponse = unknown;

export type MarkAllAsReadResponse = unknown;

export type RegisterFcmTokenData = {
    requestBody: RegisterFcmTokenRequest;
};

export type RegisterFcmTokenResponse = unknown;

export type CreateSepayPaymentData = {
    requestBody: {
        orderId: string;
        /**
         * VND
         */
        amount: number;
    };
};

export type CreateSepayPaymentResponse = {
    transactionRef?: string;
    qrCodeUrl?: string;
    amount?: number;
    expiresAt?: string;
};

export type CheckSepayStatusData = {
    transactionRef: string;
};

export type CheckSepayStatusResponse = {
    status?: 'pending' | 'completed' | 'failed';
    /**
     * VND
     */
    amount?: number;
    paidAt?: string;
};

export type GetPendingPayoutsData = {
    limit?: number;
    page?: number;
};

export type GetPendingPayoutsResponse = {
    data?: Array<PayoutLedgerEntry>;
    meta?: PaginationMeta;
};

export type GetSettlementBatchesData = {
    limit?: number;
    page?: number;
};

export type GetSettlementBatchesResponse = {
    data?: Array<SettlementBatch>;
    meta?: PaginationMeta;
};

export type SettleBatchData = {
    id: string;
    requestBody: SettleRequest;
};

export type SettleBatchResponse = SettlementBatch;

export type ForceManualPayoutData = {
    requestBody: {
        restaurantId: string;
        /**
         * VND
         */
        amount: number;
        reason: string;
    };
};

export type ForceManualPayoutResponse = unknown;

export type GetAdminDashboardResponse = DashboardResponse;

export type GetTopRestaurantsData = {
    days?: number;
};

export type GetTopRestaurantsResponse = Array<TopRestaurantEntry>;

export type GetRevenueChartData = {
    days?: number;
};

export type GetRevenueChartResponse = Array<RevenueChartEntry>;

export type GetAdminOrdersData = {
    limit?: number;
    page?: number;
    status?: string;
};

export type GetAdminOrdersResponse = OrderListResponse;

export type GetAdminUsersData = {
    limit?: number;
    page?: number;
    role?: 'customer' | 'driver' | 'restaurant' | 'admin';
};

export type GetAdminUsersResponse = AdminUserListResponse;

export type ToggleUserStatusData = {
    id: string;
    requestBody: ToggleUserStatusRequest;
};

export type ToggleUserStatusResponse = unknown;

export type GetAdminRestaurantsData = {
    limit?: number;
    page?: number;
};

export type GetAdminRestaurantsResponse = AdminRestaurantListResponse;

export type ToggleRestaurantStatusData = {
    id: string;
    requestBody: ToggleRestaurantStatusRequest;
};

export type ToggleRestaurantStatusResponse = unknown;

export type GetSupportTicketsData = {
    limit?: number;
    page?: number;
    status?: 'open' | 'in_progress' | 'resolved' | 'closed';
};

export type GetSupportTicketsResponse = SupportTicketListResponse;

export type UpdateSupportTicketData = {
    id: string;
    requestBody: UpdateSupportTicketRequest;
};

export type UpdateSupportTicketResponse = unknown;

export type GetAuditLogsData = {
    limit?: number;
    page?: number;
};

export type GetAuditLogsResponse = AuditLogListResponse;

export type GetAdminPromotionsData = {
    isActive?: boolean;
    limit?: number;
    page?: number;
};

export type GetAdminPromotionsResponse = PromotionListResponse;

export type CreatePromotionData = {
    requestBody: CreatePromotionRequest;
};

export type CreatePromotionResponse = PromotionResponse;

export type UpdatePromotionData = {
    id: string;
    requestBody: UpdatePromotionRequest;
};

export type UpdatePromotionResponse = PromotionResponse;

export type DeletePromotionData = {
    id: string;
};

export type DeletePromotionResponse = void;

export type TogglePromotionActiveData = {
    id: string;
};

export type TogglePromotionActiveResponse = PromotionResponse;

export type GetDispatchHeatmapData = {
    since?: string;
};

export type GetDispatchHeatmapResponse = DispatchHeatmapResponse;

export type GetRestaurantKpiData = {
    id: string;
    period?: '1d' | '7d' | '30d' | '90d';
};

export type GetRestaurantKpiResponse = RestaurantKpiResponse;

export type GetOnlineDriversResponse = Array<{
    driverId?: string;
    lat?: number;
    lng?: number;
    status?: string;
    orderId?: string;
    rating?: number;
}>;

export type GetAnalyticsSummaryData = {
    periodEnd?: string;
    periodStart?: string;
};

export type GetAnalyticsSummaryResponse = AnalyticsSummary;

export type AiChatData = {
    requestBody: ChatRequest;
};

export type AiChatResponse = ChatResponse;

export type AiChatStreamData = {
    requestBody: ChatRequest;
};

export type AiChatStreamResponse = string;

export type CreateSupportTicketData = {
    requestBody: {
        issueType: 'late_delivery' | 'wrong_item' | 'missing_item' | 'driver_issue' | 'refund_request' | 'other';
        summary: string;
        orderId?: string;
        priority?: 'low' | 'medium' | 'high' | 'critical';
    };
};

export type CreateSupportTicketResponse = SupportTicketEntry;

export type GetMySupportTicketsData = {
    limit?: number;
    page?: number;
};

export type GetMySupportTicketsResponse = SupportTicketListResponse;

export type N8nOrderEventData = {
    requestBody: WebhookOrderEvent;
};

export type N8nOrderEventResponse = unknown;

export type N8nDriverDelayData = {
    requestBody: WebhookDriverDelay;
};

export type N8nDriverDelayResponse = unknown;

export type GetDelayedOrdersData = {
    threshold?: number;
};

export type GetDelayedOrdersResponse = unknown;

export type GetStoppedDriversData = {
    minutes?: number;
};

export type GetStoppedDriversResponse = unknown;

export type GetLapsedCustomersData = {
    days?: number;
};

export type GetLapsedCustomersResponse = unknown;

export type SepayPaymentSuccessData = {
    requestBody: {
        transaction_ref?: string;
        amount?: number;
        status?: string;
    };
    /**
     * HMAC signature of request body (sepay provider sign)
     */
    xSepaySignature?: string;
};

export type SepayPaymentSuccessResponse = SepayWebhookResponse;

export type HealthCheckResponse = HealthResponse;

export type GetMetricsResponse = string;

export type $OpenApiTs = {
    '/auth/register': {
        post: {
            req: RegisterData;
            res: {
                /**
                 * User registered
                 */
                201: AuthResult;
                400: unknown;
                /**
                 * Email already exists
                 */
                409: ProblemDetail;
                /**
                 * Rate limited (3/min for register)
                 */
                429: unknown;
            };
        };
    };
    '/auth/login': {
        post: {
            req: LoginData;
            res: {
                /**
                 * Login successful
                 */
                200: AuthResult;
                /**
                 * Invalid credentials
                 */
                401: ProblemDetail;
                /**
                 * Account locked due to too many failed attempts
                 */
                423: ProblemDetail;
                /**
                 * Rate limited (5/min per IP)
                 */
                429: unknown;
            };
        };
    };
    '/auth/refresh': {
        post: {
            req: RefreshTokenData;
            res: {
                /**
                 * Token refreshed
                 */
                200: AuthResult;
                /**
                 * Invalid or reused refresh token
                 */
                401: ProblemDetail;
            };
        };
    };
    '/auth/logout': {
        post: {
            req: LogoutData;
            res: {
                /**
                 * Logged out
                 */
                200: {
                    message?: string;
                };
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/auth/jwks': {
        get: {
            res: {
                /**
                 * JWKS keys
                 */
                200: JwksResponse;
            };
        };
    };
    '/auth/jwks-version': {
        get: {
            res: {
                /**
                 * JWKS version info
                 */
                200: JwksVersionResponse;
            };
        };
    };
    '/users/me': {
        get: {
            res: {
                /**
                 * User profile
                 */
                200: UserProfile;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
        patch: {
            req: UpdateProfileData;
            res: {
                /**
                 * Profile updated
                 */
                200: UserProfile;
                /**
                 * Validation error
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/users/me/avatar': {
        post: {
            req: UploadAvatarData;
            res: {
                /**
                 * Avatar uploaded
                 */
                200: AvatarUploadResponse;
                /**
                 * No file or invalid format
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/users/me/addresses': {
        get: {
            res: {
                /**
                 * Address list
                 */
                200: Array<Address>;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
        post: {
            req: CreateAddressData;
            res: {
                /**
                 * Address created
                 */
                201: Address;
                /**
                 * Validation error
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/users/me/addresses/{id}': {
        patch: {
            req: UpdateAddressData;
            res: {
                /**
                 * Address updated
                 */
                200: Address;
                /**
                 * Validation error
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Address not found
                 */
                404: unknown;
            };
        };
        delete: {
            req: DeleteAddressData;
            res: {
                /**
                 * Address deleted
                 */
                204: void;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Address not found
                 */
                404: unknown;
            };
        };
    };
    '/restaurants/nearby': {
        get: {
            req: FindNearbyRestaurantsData;
            res: {
                /**
                 * Nearby restaurants
                 */
                200: RestaurantListResponse;
            };
        };
    };
    '/restaurants/search': {
        get: {
            req: SearchRestaurantsData;
            res: {
                /**
                 * Search results
                 */
                200: RestaurantListResponse;
            };
        };
    };
    '/restaurants/{id}': {
        get: {
            req: GetRestaurantDetailData;
            res: {
                /**
                 * Restaurant detail
                 */
                200: RestaurantDetail;
                /**
                 * Restaurant not found
                 */
                404: unknown;
            };
        };
    };
    '/restaurants/{id}/menu': {
        get: {
            req: GetRestaurantMenuData;
            res: {
                /**
                 * Restaurant menu
                 */
                200: MenuResponse;
                /**
                 * Restaurant not found
                 */
                404: unknown;
            };
        };
    };
    '/restaurants/{id}/reviews': {
        get: {
            req: GetRestaurantReviewsData;
            res: {
                /**
                 * Restaurant reviews
                 */
                200: ReviewListResponse;
                /**
                 * Restaurant not found
                 */
                404: unknown;
            };
        };
    };
    '/restaurant/menu': {
        get: {
            res: {
                /**
                 * Full menu with categories and items
                 */
                200: MenuResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not a restaurant owner
                 */
                403: unknown;
            };
        };
    };
    '/restaurant/menu/categories': {
        post: {
            req: CreateCategoryData;
            res: {
                /**
                 * Category created
                 */
                201: MenuCategory;
                /**
                 * Validation error
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not a restaurant owner
                 */
                403: unknown;
            };
        };
    };
    '/restaurant/menu/categories/{id}': {
        patch: {
            req: UpdateCategoryData;
            res: {
                /**
                 * Category updated
                 */
                200: unknown;
                /**
                 * Validation error
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not a restaurant owner
                 */
                403: unknown;
                /**
                 * Category not found
                 */
                404: unknown;
            };
        };
        delete: {
            req: DeleteCategoryData;
            res: {
                /**
                 * Category deleted
                 */
                204: void;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not a restaurant owner
                 */
                403: unknown;
                /**
                 * Category not found
                 */
                404: unknown;
            };
        };
    };
    '/restaurant/menu/items': {
        post: {
            req: CreateMenuItemData;
            res: {
                /**
                 * Menu item created
                 */
                201: MenuItem;
                /**
                 * Validation error
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not a restaurant owner
                 */
                403: unknown;
            };
        };
    };
    '/restaurant/menu/items/{id}': {
        patch: {
            req: UpdateMenuItemData;
            res: {
                /**
                 * Menu item updated
                 */
                200: MenuItem;
                /**
                 * Validation error
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not a restaurant owner
                 */
                403: unknown;
                /**
                 * Menu item not found
                 */
                404: unknown;
            };
        };
        delete: {
            req: DeleteMenuItemData;
            res: {
                /**
                 * Menu item deleted
                 */
                204: void;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not a restaurant owner
                 */
                403: unknown;
                /**
                 * Menu item not found
                 */
                404: unknown;
            };
        };
    };
    '/cart': {
        get: {
            res: {
                /**
                 * Current cart
                 */
                200: CartResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
        delete: {
            res: {
                /**
                 * Cart cleared
                 */
                204: void;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/cart/items': {
        post: {
            req: AddCartItemData;
            res: {
                /**
                 * Item added
                 */
                201: CartResponse;
                /**
                 * Validation error
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/cart/items/{id}': {
        patch: {
            req: UpdateCartItemData;
            res: {
                /**
                 * Item updated
                 */
                200: CartResponse;
                /**
                 * Validation error
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Cart item not found
                 */
                404: unknown;
            };
        };
        delete: {
            req: RemoveCartItemData;
            res: {
                /**
                 * Item removed
                 */
                204: void;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Cart item not found
                 */
                404: unknown;
            };
        };
    };
    '/cart/apply-promotion': {
        post: {
            req: ApplyPromotionData;
            res: {
                /**
                 * Promotion applied
                 */
                200: CartResponse;
                /**
                 * Invalid or expired code
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/orders': {
        post: {
            req: PlaceOrderData;
            res: {
                /**
                 * Order placed
                 */
                201: OrderResponse;
                /**
                 * Validation error or cart empty
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Insufficient wallet balance
                 */
                402: unknown;
                /**
                 * Duplicate idempotency key
                 */
                409: unknown;
                /**
                 * Restaurant not accepting orders
                 */
                422: unknown;
            };
        };
        get: {
            req: GetCustomerOrdersData;
            res: {
                /**
                 * Order list
                 */
                200: OrderListResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/orders/{id}': {
        get: {
            req: GetOrderDetailData;
            res: {
                /**
                 * Order detail
                 */
                200: OrderResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not authorized to view this order
                 */
                403: unknown;
                /**
                 * Order not found
                 */
                404: unknown;
            };
        };
    };
    '/orders/{id}/tracking': {
        get: {
            req: GetOrderTrackingData;
            res: {
                /**
                 * Tracking data
                 */
                200: TrackingResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Order not found or no driver assigned
                 */
                404: unknown;
            };
        };
    };
    '/orders/{id}/cancel': {
        post: {
            req: CancelOrderData;
            res: {
                /**
                 * Order cancelled
                 */
                200: OrderResponse;
                /**
                 * Order cannot be cancelled at this stage
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Order not found
                 */
                404: unknown;
            };
        };
    };
    '/orders/{id}/review': {
        post: {
            req: SubmitReviewData;
            res: {
                /**
                 * Review submitted
                 */
                201: ReviewResponse;
                /**
                 * Order not eligible for review
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Review already submitted for this order
                 */
                409: unknown;
            };
        };
    };
    '/restaurant/orders': {
        get: {
            req: GetRestaurantOrdersData;
            res: {
                /**
                 * Restaurant orders
                 */
                200: Array<OrderResponse>;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not a restaurant owner
                 */
                403: unknown;
            };
        };
    };
    '/restaurant/orders/{id}/status': {
        patch: {
            req: UpdateRestaurantOrderStatusData;
            res: {
                /**
                 * Status updated
                 */
                200: OrderResponse;
                /**
                 * Invalid status transition
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not authorized
                 */
                403: unknown;
                /**
                 * Order not found
                 */
                404: unknown;
            };
        };
    };
    '/driver/orders/{id}/status': {
        patch: {
            req: UpdateDriverOrderStatusData;
            res: {
                /**
                 * Status updated
                 */
                200: OrderResponse;
                /**
                 * Invalid status transition
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not authorized
                 */
                403: unknown;
                /**
                 * Order not found
                 */
                404: unknown;
            };
        };
    };
    '/driver/dispatch/pending': {
        get: {
            res: {
                /**
                 * Pending offers
                 */
                200: Array<DispatchOffer>;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not a driver
                 */
                403: unknown;
            };
        };
    };
    '/driver/dispatch/{orderId}/accept': {
        post: {
            req: AcceptOfferData;
            res: {
                /**
                 * Offer accepted
                 */
                200: OrderResponse;
                /**
                 * Offer expired or already claimed
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not a driver
                 */
                403: unknown;
            };
        };
    };
    '/driver/online': {
        post: {
            req: GoOnlineData;
            res: {
                /**
                 * Now online
                 */
                200: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not a verified driver
                 */
                403: unknown;
            };
        };
    };
    '/driver/offline': {
        post: {
            res: {
                /**
                 * Now offline
                 */
                200: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/driver/earnings': {
        get: {
            req: GetDriverEarningsData;
            res: {
                /**
                 * Earnings summary
                 */
                200: DriverEarningsResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not a driver
                 */
                403: unknown;
            };
        };
    };
    '/driver/incentives': {
        get: {
            res: {
                /**
                 * Active incentives
                 */
                200: DriverIncentivesResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not a driver
                 */
                403: unknown;
            };
        };
    };
    '/driver/orders/history': {
        get: {
            req: GetDriverOrderHistoryData;
            res: {
                /**
                 * Driver orders
                 */
                200: OrderListResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not a driver
                 */
                403: unknown;
            };
        };
    };
    '/users/wallet': {
        get: {
            res: {
                /**
                 * Wallet snapshot
                 */
                200: WalletSnapshot;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/users/wallet/topup': {
        post: {
            req: TopupWalletData;
            res: {
                /**
                 * Topup initiated
                 */
                200: {
                    transactionRef?: string;
                    qrCodeUrl?: string;
                    amount?: number;
                    expiresAt?: string;
                };
                /**
                 * Invalid amount
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/users/wallet/topup/{transactionRef}/status': {
        get: {
            req: CheckTopupStatusData;
            res: {
                /**
                 * Topup status
                 */
                200: {
                    status?: 'pending' | 'completed' | 'failed';
                    amount?: number;
                };
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Transaction not found
                 */
                404: unknown;
            };
        };
    };
    '/users/loyalty': {
        get: {
            res: {
                /**
                 * Loyalty snapshot
                 */
                200: LoyaltySnapshot;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/users/referral': {
        get: {
            res: {
                /**
                 * Referral snapshot
                 */
                200: ReferralSnapshot;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/promotions/{code}': {
        get: {
            req: GetPromotionByCodeData;
            res: {
                /**
                 * Promotion detail with calculated discount if applicable
                 */
                200: PromotionResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Promotion not found or expired
                 */
                404: unknown;
            };
        };
    };
    '/promotions': {
        get: {
            req: ListPromotionsData;
            res: {
                /**
                 * Active promotions
                 */
                200: PromotionListResponse;
            };
        };
    };
    '/reviews/photos/upload-url': {
        get: {
            req: GetPhotoUploadUrlData;
            res: {
                /**
                 * Upload URL
                 */
                200: ReviewPhotoUploadUrlResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/reviews/{id}/hide': {
        patch: {
            req: AdminHideReviewData;
            res: {
                /**
                 * Review hidden
                 */
                204: void;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
                /**
                 * Review not found
                 */
                404: unknown;
            };
        };
    };
    '/restaurant/reviews/{id}/reply': {
        post: {
            req: RestaurantReplyData;
            res: {
                /**
                 * Reply posted
                 */
                200: ReviewResponse;
                /**
                 * Validation error
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not the order's restaurant
                 */
                403: unknown;
                /**
                 * Review not found
                 */
                404: unknown;
            };
        };
    };
    '/notifications': {
        get: {
            req: GetNotificationsData;
            res: {
                /**
                 * Notification list
                 */
                200: NotificationListResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/notifications/{id}/read': {
        patch: {
            req: MarkAsReadData;
            res: {
                /**
                 * Marked as read
                 */
                200: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Notification not found
                 */
                404: unknown;
            };
        };
    };
    '/notifications/read-all': {
        patch: {
            res: {
                /**
                 * All marked as read
                 */
                200: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/notifications/fcm-token': {
        post: {
            req: RegisterFcmTokenData;
            res: {
                /**
                 * Token registered
                 */
                201: unknown;
                /**
                 * Validation error
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/payments/sepay/create': {
        post: {
            req: CreateSepayPaymentData;
            res: {
                /**
                 * Payment intent created
                 */
                200: {
                    transactionRef?: string;
                    qrCodeUrl?: string;
                    amount?: number;
                    expiresAt?: string;
                };
                /**
                 * Invalid order or already paid
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/payments/sepay/status/{transactionRef}': {
        get: {
            req: CheckSepayStatusData;
            res: {
                /**
                 * Payment status
                 */
                200: {
                    status?: 'pending' | 'completed' | 'failed';
                    /**
                     * VND
                     */
                    amount?: number;
                    paidAt?: string;
                };
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Transaction not found
                 */
                404: unknown;
            };
        };
    };
    '/admin/payments/pending': {
        get: {
            req: GetPendingPayoutsData;
            res: {
                /**
                 * Pending payout entries
                 */
                200: {
                    data?: Array<PayoutLedgerEntry>;
                    meta?: PaginationMeta;
                };
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
            };
        };
    };
    '/admin/payments/settlement-batches': {
        get: {
            req: GetSettlementBatchesData;
            res: {
                /**
                 * Settlement batches
                 */
                200: {
                    data?: Array<SettlementBatch>;
                    meta?: PaginationMeta;
                };
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
            };
        };
    };
    '/admin/payments/settlement-batches/{id}/settle': {
        post: {
            req: SettleBatchData;
            res: {
                /**
                 * Settlement processed
                 */
                200: SettlementBatch;
                /**
                 * Invalid action or batch state
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
                /**
                 * Batch not found
                 */
                404: unknown;
            };
        };
    };
    '/admin/payments/payouts/manual': {
        post: {
            req: ForceManualPayoutData;
            res: {
                /**
                 * Manual payout queued
                 */
                200: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
            };
        };
    };
    '/admin/dashboard': {
        get: {
            res: {
                /**
                 * Dashboard summary
                 */
                200: DashboardResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
            };
        };
    };
    '/admin/dashboard/top-restaurants': {
        get: {
            req: GetTopRestaurantsData;
            res: {
                /**
                 * Top restaurants
                 */
                200: Array<TopRestaurantEntry>;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
            };
        };
    };
    '/admin/dashboard/revenue-chart': {
        get: {
            req: GetRevenueChartData;
            res: {
                /**
                 * Revenue chart data
                 */
                200: Array<RevenueChartEntry>;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
            };
        };
    };
    '/admin/orders': {
        get: {
            req: GetAdminOrdersData;
            res: {
                /**
                 * Orders list
                 */
                200: OrderListResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
            };
        };
    };
    '/admin/users': {
        get: {
            req: GetAdminUsersData;
            res: {
                /**
                 * Users list
                 */
                200: AdminUserListResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
            };
        };
    };
    '/admin/users/{id}/status': {
        patch: {
            req: ToggleUserStatusData;
            res: {
                /**
                 * User status toggled
                 */
                200: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
                /**
                 * User not found
                 */
                404: unknown;
            };
        };
    };
    '/admin/restaurants': {
        get: {
            req: GetAdminRestaurantsData;
            res: {
                /**
                 * Restaurants list
                 */
                200: AdminRestaurantListResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
            };
        };
    };
    '/admin/restaurants/{id}/status': {
        patch: {
            req: ToggleRestaurantStatusData;
            res: {
                /**
                 * Restaurant status toggled
                 */
                200: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
                /**
                 * Restaurant not found
                 */
                404: unknown;
            };
        };
    };
    '/admin/support-tickets': {
        get: {
            req: GetSupportTicketsData;
            res: {
                /**
                 * Tickets list
                 */
                200: SupportTicketListResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
            };
        };
    };
    '/admin/support-tickets/{id}': {
        patch: {
            req: UpdateSupportTicketData;
            res: {
                /**
                 * Ticket updated
                 */
                200: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
                /**
                 * Ticket not found
                 */
                404: unknown;
            };
        };
    };
    '/admin/audit-logs': {
        get: {
            req: GetAuditLogsData;
            res: {
                /**
                 * Audit logs
                 */
                200: AuditLogListResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
            };
        };
    };
    '/admin/promotions': {
        get: {
            req: GetAdminPromotionsData;
            res: {
                /**
                 * Promotions list
                 */
                200: PromotionListResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
            };
        };
        post: {
            req: CreatePromotionData;
            res: {
                /**
                 * Promotion created
                 */
                201: PromotionResponse;
                /**
                 * Validation error
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
            };
        };
    };
    '/admin/promotions/{id}': {
        patch: {
            req: UpdatePromotionData;
            res: {
                /**
                 * Promotion updated
                 */
                200: PromotionResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
                /**
                 * Promotion not found
                 */
                404: unknown;
            };
        };
        delete: {
            req: DeletePromotionData;
            res: {
                /**
                 * Promotion deleted
                 */
                204: void;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
                /**
                 * Promotion not found
                 */
                404: unknown;
            };
        };
    };
    '/admin/promotions/{id}/toggle': {
        patch: {
            req: TogglePromotionActiveData;
            res: {
                /**
                 * Promotion toggled
                 */
                200: PromotionResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
                /**
                 * Promotion not found
                 */
                404: unknown;
            };
        };
    };
    '/admin/dispatch/heatmap': {
        get: {
            req: GetDispatchHeatmapData;
            res: {
                /**
                 * Heatmap data
                 */
                200: DispatchHeatmapResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
            };
        };
    };
    '/admin/restaurants/{id}/kpi': {
        get: {
            req: GetRestaurantKpiData;
            res: {
                /**
                 * Restaurant KPI
                 */
                200: RestaurantKpiResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
                /**
                 * Restaurant not found
                 */
                404: unknown;
            };
        };
    };
    '/admin/online-drivers': {
        get: {
            res: {
                /**
                 * Online drivers
                 */
                200: Array<{
                    driverId?: string;
                    lat?: number;
                    lng?: number;
                    status?: string;
                    orderId?: string;
                    rating?: number;
                }>;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
            };
        };
    };
    '/admin/analytics': {
        get: {
            req: GetAnalyticsSummaryData;
            res: {
                /**
                 * Analytics summary
                 */
                200: AnalyticsSummary;
                /**
                 * Not authenticated
                 */
                401: unknown;
                /**
                 * Not an admin
                 */
                403: unknown;
            };
        };
    };
    '/ai/chat': {
        post: {
            req: AiChatData;
            res: {
                /**
                 * Chat response
                 */
                200: ChatResponse;
                /**
                 * Empty message
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/ai/stream': {
        post: {
            req: AiChatStreamData;
            res: {
                /**
                 * SSE stream of tokens
                 */
                200: string;
                /**
                 * Empty or injection message
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/support/tickets': {
        post: {
            req: CreateSupportTicketData;
            res: {
                /**
                 * Ticket created
                 */
                201: SupportTicketEntry;
                /**
                 * Validation error
                 */
                400: unknown;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
        get: {
            req: GetMySupportTicketsData;
            res: {
                /**
                 * My tickets
                 */
                200: SupportTicketListResponse;
                /**
                 * Not authenticated
                 */
                401: unknown;
            };
        };
    };
    '/webhooks/n8n/order-event': {
        post: {
            req: N8nOrderEventData;
            res: {
                /**
                 * Received
                 */
                200: unknown;
                /**
                 * Invalid API key
                 */
                401: unknown;
            };
        };
    };
    '/webhooks/n8n/driver-delay': {
        post: {
            req: N8nDriverDelayData;
            res: {
                /**
                 * Received
                 */
                200: unknown;
                /**
                 * Invalid API key
                 */
                401: unknown;
            };
        };
    };
    '/webhooks/delayed-orders': {
        get: {
            req: GetDelayedOrdersData;
            res: {
                /**
                 * Delayed orders list
                 */
                200: unknown;
                /**
                 * Invalid API key
                 */
                401: unknown;
            };
        };
    };
    '/webhooks/stopped-drivers': {
        get: {
            req: GetStoppedDriversData;
            res: {
                /**
                 * Stopped drivers list
                 */
                200: unknown;
                /**
                 * Invalid API key
                 */
                401: unknown;
            };
        };
    };
    '/webhooks/lapsed-customers': {
        get: {
            req: GetLapsedCustomersData;
            res: {
                /**
                 * Lapsed customers list
                 */
                200: unknown;
                /**
                 * Invalid API key
                 */
                401: unknown;
            };
        };
    };
    '/webhooks/sepay/payment-success': {
        post: {
            req: SepayPaymentSuccessData;
            res: {
                /**
                 * Payment processed
                 */
                200: SepayWebhookResponse;
                /**
                 * Invalid signature or missing transaction_ref
                 */
                400: unknown;
            };
        };
    };
    '/healthz': {
        get: {
            res: {
                /**
                 * All components up
                 */
                200: HealthResponse;
                /**
                 * Degraded
                 */
                503: HealthResponse;
            };
        };
    };
    '/metrics': {
        get: {
            res: {
                /**
                 * Prometheus text format metrics
                 */
                200: string;
            };
        };
    };
};